primeira=float(input("Digite a primeira nota: "))
segunda=float(input("Digite a segunda nota: "))
terceira=float(input("Digite a terceira nota: "))
quarta=float(input("Digite a quarta nota: "))
print("A média aritmética é", (primeira+segunda+terceira+quarta)/4)
